"""Metadata formatting utilities for combining AI-generated content with context."""

from typing import List, Optional
import logging

logger = logging.getLogger(__name__)


class MetadataFormatter:
    """Format and combine metadata from multiple sources.

    This class handles:
    - Combining AI-generated captions with EXIF location data
    - Integrating person names from face recognition
    - Merging new tags with existing tags
    - Formatting final metadata for SmugMug API
    """

    def __init__(self, preserve_existing: bool = True, marker_tag: str = "smugvision") -> None:
        """Initialize metadata formatter.

        Args:
            preserve_existing: If True, preserve existing captions and merge tags
            marker_tag: Tag to mark processed images
        """
        self.preserve_existing = preserve_existing
        self.marker_tag = marker_tag
        logger.debug(
            f"MetadataFormatter initialized: preserve_existing={preserve_existing}, "
            f"marker_tag={marker_tag}"
        )

    def format_caption(
        self,
        ai_caption: str,
        existing_caption: Optional[str] = None,
        location: Optional[str] = None,
        person_names: Optional[List[str]] = None,
    ) -> str:
        """Format final caption combining all sources.

        Args:
            ai_caption: Caption generated by vision model
            existing_caption: Existing caption from SmugMug (if any)
            location: Location name from EXIF geocoding
            person_names: List of identified person names from face recognition

        Returns:
            Formatted caption string
        """
        caption_parts = []

        # Start with existing caption if preserving
        if self.preserve_existing and existing_caption:
            caption_parts.append(existing_caption.strip())

        # Add AI-generated caption
        if ai_caption:
            caption_text = ai_caption.strip()

            # Add person names, but only those the model did not already name itself.
            # Vision models are given the recognized names as prompt context and now
            # usually work them into the sentence, so appending them unconditionally
            # produced "Eric Pullen smiles ... Featuring Eric Pullen."
            if person_names:
                unmentioned = [
                    name for name in person_names if not self._mentions(caption_text, name)
                ]
                if unmentioned:
                    names_str = self._format_person_names(unmentioned)
                    # Insert person names naturally into caption
                    # If caption starts with "A photo of" or similar, insert after it
                    if caption_text.lower().startswith(("a photo", "an image", "a picture")):
                        # Find the end of the first phrase
                        if " of " in caption_text.lower()[:20]:
                            insert_pos = caption_text.lower().index(" of ") + 4
                            caption_text = (
                                caption_text[:insert_pos]
                                + names_str
                                + " "
                                + caption_text[insert_pos:]
                            )
                        else:
                            caption_text = f"{caption_text} Featuring {names_str}."
                    else:
                        # Append person names
                        caption_text = f"{caption_text} Featuring {names_str}."

            # Add location if available and not already in caption
            if location and not self._mentions_location(caption_text, location):
                # Check if caption already ends with location-like text
                if not caption_text.rstrip(".").endswith(("at", "in", "near", "from")):
                    caption_text = f"{caption_text.rstrip('.')} at {location}."

            caption_parts.append(caption_text)

        # Join parts with separator if multiple
        if len(caption_parts) > 1:
            final_caption = " | ".join(caption_parts)
        elif caption_parts:
            final_caption = caption_parts[0]
        else:
            final_caption = ""

        logger.debug(f"Formatted caption: {final_caption[:100]}...")
        return final_caption

    def format_tags(
        self,
        ai_tags: List[str],
        existing_tags: Optional[List[str]] = None,
        person_names: Optional[List[str]] = None,
        location_tags: Optional[List[str]] = None,
        pet_names: Optional[List[str]] = None,
    ) -> List[str]:
        """Format final tag list combining all sources.

        Args:
            ai_tags: Tags generated by vision model
            existing_tags: Existing tags from SmugMug
            person_names: Person names to add as tags
            location_tags: Location-based tags (city, state, venue name)
            pet_names: Pet names to add as tags. Separate from person_names so a pet is
                never fed to anything that reasons about faces or people.

        Returns:
            List of unique tags
        """
        # Start with existing tags if preserving
        if self.preserve_existing and existing_tags:
            tags = [tag.strip() for tag in existing_tags if tag.strip()]
        else:
            tags = []

        # Add AI-generated tags
        if ai_tags:
            tags.extend([tag.strip() for tag in ai_tags if tag.strip()])

        # Add person name tags
        if person_names:
            tags.extend(person_names)

        # Add pet name tags
        if pet_names:
            tags.extend(pet_names)

        # Add location tags
        if location_tags:
            tags.extend(location_tags)

        # Remove duplicates while preserving order (case-insensitive)
        seen = set()
        unique_tags = []
        for tag in tags:
            tag_lower = tag.lower()
            if tag_lower not in seen and tag_lower != self.marker_tag.lower():
                seen.add(tag_lower)
                unique_tags.append(tag)

        # Add marker tag at the end
        unique_tags.append(self.marker_tag)

        logger.debug(f"Formatted {len(unique_tags)} tags (including marker)")
        return unique_tags

    @staticmethod
    def _mentions(text: str, needle: str) -> bool:
        """Test whether text already contains a name or place, case-insensitively.

        Args:
            text: Caption text to search
            needle: Person name or place name to look for

        Returns:
            True if ``needle`` appears in ``text``
        """
        return bool(needle) and needle.lower() in text.lower()

    @classmethod
    def _mentions_location(cls, text: str, location: str) -> bool:
        """Test whether a caption already names a location.

        The full location string rarely matches verbatim: geocoding yields
        "Louisville Zoo, Louisville, Kentucky" while a model writes "at the Louisville
        Zoo in Louisville, Kentucky". Comparing only the whole string therefore let the
        venue be appended a second time. The first comma-separated component is the
        specific, informative part, so it is checked as well.

        Args:
            text: Caption text to search
            location: Resolved location string, possibly comma-separated

        Returns:
            True if the caption already names this location
        """
        if cls._mentions(text, location):
            return True
        primary = location.split(",")[0].strip()
        # Ignore very short leading components; matching a 2-3 character token would
        # produce false positives against ordinary words.
        return len(primary) > 3 and cls._mentions(text, primary)

    def _format_person_names(self, names: List[str]) -> str:
        """Format list of person names for natural language.

        Args:
            names: List of person names

        Returns:
            Formatted string like "Alice", "Alice and Bob", or "Alice, Bob, and Charlie"
        """
        if not names:
            return ""
        if len(names) == 1:
            return names[0]
        if len(names) == 2:
            return f"{names[0]} and {names[1]}"
        # Three or more names
        return ", ".join(names[:-1]) + f", and {names[-1]}"
